language: android

notifications:
  email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pax

sudo: false

env:
  global:
  - ANDROID_API_LEVEL=27
  - ANDROID_BUILD_TOOLS_VERSION=27.0.3
  - ANDROID_EMU_API_LEVEL=22
  - ANDROID_ABI=armeabi-v7a
  - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
  - QEMU_AUDIO_DRV=none # Remove audio

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$ANDROID_EMU_API_LEVEL
  - extra-android-support
  - sys-img-$ANDROID_ABI-google_apis-$ANDROID_API_LEVEL
  - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL

before_script:
  - echo -e "Host github.com\n\tHostName github.com\n\tUser git\n\tIdentityFile ~/.ssh/id_travisci\n" >> ~/.ssh/config
  - android list targets
#  - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi $ANDROID_ABI --tag google_apis
#  - emulator -avd test -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &

script:
  - chmod +x gradlew
  # - ./gradlew clean build test cAT
